name: Deployment

on:
  workflow_run:
    workflows: ["Tests"]
    branches: ["main"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Sending request
      run: |
        status=$(curl -s -o /dev/null -I -w "%{http_code}" -X POST https://friendhub.social/api/deploy?key=${{ secrets.DEPLOY_KEY }})
        echo "Got status code" $status
        if [[ $((status)) -ge 400 ]]; then
            exit 1
        else
            exit 0
        fi
