name: ruff

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install ruff
        pip install -r friendhub/backend/config/requirements.txt
    - name: Running black
      run: |
        PYTHONPATH="friendhub/backend/src" black friendhub/backend/src/
    - name: Analyzing the code with ruff
      run: |
        PYTHONPATH="friendhub/src:." ruff friendhub/backend/src/
